language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - WILDFLY="8.0.0.CR1"
    - JBOSS_HOME=$HOME/wildfly-$WILDFLY
    - PROFILES="it,wildfly-it-travis"
    - secure: WrQYhD3HBLqpKj83AxUH+Gf1EL1vlAX/kcfTAMPSJdjyIcYR/U1b0BYl9ne8Glro8UopZrH8X+3I0oP6GXXG7ihnb8L2sawCutC9EyccQOvFcfuMttSMhTpJpnLSLqEw5Gdp3qb4WDHOFALfo0G4hd/Yr2iIxSp/x6DQAuIz76M=

cache:
  directories:
    - $HOME/.m2

before_script:
  - export ROOT_DIR=`pwd`
  - cd $HOME
  - wget http://download.jboss.org/wildfly/$WILDFLY/wildfly-$WILDFLY.tar.gz
  - tar xfz wildfly-$WILDFLY.tar.gz
  - cd $ROOT_DIR
  - cp carcv-webapp/src/test/resources/wildfly_configuration_standalone/standalone.xml $JBOSS_HOME/standalone/configuration/standalone.xml

script: "mvn clean verify -P$PROFILES"

install: /bin/true

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura -P$PROFILES

notifications:
  irc:
    channels:
      - "irc.freenode.org#carcv"
    on_success: change
    on_failure: always
    template:
      - '%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})'
